### ISSUE TITLE
Changing interfaceA with interfaceB

### ISSUE THREAD

**Issue by interduo** [LibreQoE/LibreQoS#172]
Today I was changing the interfaceA with interfaceB. 

This generated an error.
```
root@rty-libreqos:~# /root/LibreQoS/v1.2/LibreQoS.py
refreshShapers starting at 02/12/2022 14:01:01
First time run since system boot.
Traceback (most recent call last):
  File "/root/LibreQoS/v1.2/LibreQoS.py", line 911, in <module>
    refreshShapers()
  File "/root/LibreQoS/v1.2/LibreQoS.py", line 257, in refreshShapers
    if (validateNetworkAndDevices() == True):
  File "/root/LibreQoS/v1.2/LibreQoS.py", line 104, in validateNetworkAndDevices
    with open('network.json') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'network.json'
```

I just rebooted & its working now again but ... maybe need to run some "full-full-full" reload when changing interfaces? reboot always work :D

**Comment by interduo** [comment]
Sorry for this i didn't read error message carefully.
