### ISSUE TITLE
First run of LibreQoS.py always generates an error

### ISSUE THREAD

**Issue by interduo** [LibreQoE/LibreQoS#228]
```
Finished binpacking
Generated parent nodes created
Error: Cannot delete qdisc with handle of zero.
Executing linux TC class/qdisc commands
```

Look at third line

Small thing but very frustrating when using grep

**Comment by dtaht** [comment]
@rchac this gone?

**Comment by interduo** [comment]
No - part of log from booting from /var/log/syslog

```
Mar 21 16:24:05 libreqos networkd-dispatcher[931]: No valid path found for iwconfig
Mar 21 16:24:05 libreqos networkd-dispatcher[931]: No valid path found for iw
Mar 21 16:24:05 libreqos systemd[1]: Started Dispatcher daemon for systemd-networkd.
Mar 21 16:24:05 libreqos systemd[1]: Started Simple Network Management Protocol (SNMP) Daemon..
Mar 21 16:24:05 libreqos systemd-networkd[907]: ens16f0np0: Gained carrier
Mar 21 16:24:05 libreqos systemd-timesyncd[899]: Network configuration changed, trying to establish connection.
Mar 21 16:24:05 libreqos kernel: [    6.547479] IPv6: ADDRCONF(NETDEV_CHANGE): ens16f0np0: link becomes ready
Mar 21 16:24:05 libreqos lqosd[928]: [2023-03-21T15:24:05Z INFO  lqos_sys::lqos_kernel] Unloading XDP/TC
Mar 21 16:24:05 libreqos python3[930]: thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Socket (typically /run/lqos/bus) not found. Check that lqosd is running, and you have permission to access the socket path.', lqos_python/src/lib.rs:203:70
Mar 21 16:24:05 libreqos python3[930]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Mar 21 16:24:05 libreqos python3[930]: Running Python Version 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
Mar 21 16:24:05 libreqos python3[930]: refreshShapers starting at 21/03/2023 16:24:05
Mar 21 16:24:05 libreqos python3[930]: First time run since system boot.
Mar 21 16:24:05 libreqos python3[930]: Validating input files 'ShapedDevices.csv' and 'network.json'
Mar 21 16:24:05 libreqos python3[930]: Traceback (most recent call last):
Mar 21 16:24:05 libreqos python3[930]:   File "/opt/libreqos/src/scheduler.py", line 45, in <module>
Mar 21 16:24:05 libreqos python3[930]:     importAndShapeFullReload()
Mar 21 16:24:05 libreqos python3[930]:   File "/opt/libreqos/src/scheduler.py", line 38, in importAndShapeFullReload
Mar 21 16:24:05 libreqos python3[930]:     refreshShapers()
Mar 21 16:24:05 libreqos python3[930]:   File "/opt/libreqos/src/LibreQoS.py", line 432, in refreshShapers
Mar 21 16:24:05 libreqos python3[930]:     if (validateNetworkAndDevices() == True):
Mar 21 16:24:05 libreqos python3[930]:   File "/opt/libreqos/src/LibreQoS.py", line 133, in validateNetworkAndDevices
Mar 21 16:24:05 libreqos python3[930]:     rustValid = validate_shaped_devices()
Mar 21 16:24:05 libreqos python3[930]: pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: Socket (typically /run/lqos/bus) not found. Check that lqosd is running, and you have permission to access the socket path.
Mar 21 16:24:05 libreqos systemd[1]: lqos_scheduler.service: Main process exited, code=exited, status=1/FAILURE
Mar 21 16:24:05 libreqos systemd[1]: lqos_scheduler.service: Failed with result 'exit-code'.
Mar 21 16:24:05 libreqos lqosd[928]: [2023-03-21T15:24:05Z INFO  lqos_sys::lqos_kernel] Attached in driver mode. (Fast)
Mar 21 16:24:05 libreqos lqosd[928]: [2023-03-21T15:24:05Z INFO  lqos_sys::cpu_map] xps_setup
Mar 21 16:24:05 libreqos systemd-networkd[907]: ens16f1np1: Gained IPv6LL
Mar 21 16:24:05 libreqos lqosd[928]: [2023-03-21T15:24:05Z INFO  lqos_sys::cpu_map] Mapped TX queue for CPU 0
Mar 21 16:24:05 libreqos lqosd[928]: [2023-03-21T15:24:05Z INFO  lqos_sys::cpu_map] Mapped TX queue for CPU 1
Mar 21 16:24:05 libreqos lqosd[928]: [2023-03-21T15:24:05Z INFO  lqos_sys::cpu_map] Mapped TX queue for CPU 2
Mar 21 16:24:05 libreqos lqosd[928]: [2023-03-21T15:24:05Z INFO  lqos_sys::cpu_map] Mapped TX queue for CPU 3

```

**Comment by rchac** [comment]
@interduo Your network.json file seems to be missing

**Comment by interduo** [comment]
This is not this issue @rchac please post it in https://github.com/LibreQoE/LibreQoS/issues/54

**Comment by interduo** [comment]
bigger part of log is: http://kłopotek.pl/booting_problem

**Comment by rchac** [comment]
@interduo Are you using OnAStick = True?

**Comment by interduo** [comment]
> @interduo Are you using OnAStick = True?

No

**Comment by rchac** [comment]
What version of Ubuntu are you using? I checked ```cat /var/log/syslog | grep "Cannot delete qdisc"``` and it doesn't appear on 22.04. Usually the interfaces have an fq_codel root qdisc by default which it can delete.

**Comment by interduo** [comment]
```
root@libreqos:~# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"

root@libreqos:~# uname -a
Linux libreqos 5.15.0-67-generic #74-Ubuntu SMP Wed Feb 22 14:14:39 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

```
root@libreqos:~# cat /var/log/syslog | grep "Cannot delete qdisc"
Mar 21 16:24:08 libreqos python3[1158]: Error: Cannot delete qdisc with handle of zero.
Mar 21 16:24:08 libreqos python3[1159]: Error: Cannot delete qdisc with handle of zero.
```

**Comment by dtaht** [comment]
I am thinking this is due to at some later stage, ubuntu attempting to put another qdisc on top. This is not an error for us, and we should just elide it from the logs.

**Comment by interduo** [comment]
On my desktop ubuntu I have:
```
qdisc noqueue 0: dev lo root refcnt 2 
qdisc pfifo_fast 0: dev enp0s31f6 root refcnt 2 bands 3 priomap 1 2 2 2 1 2 0 0 1 1 1 1 1 1 1 1
```
Running libreqos creates some queues:
```
qdisc mq 7fff: dev ens16f0np0 root 
qdisc mq 7fff: dev ens16f1np1 root 
```
and only this queue should be removed and not with handle 0 (because it's impossible to delete).

**Comment by rchac** [comment]
The actual commands we run on each start of LibreQoS.py (in order to clear any previous setup) are:
```
tc qdisc delete dev interfaceA root
tc qdisc delete dev interfaceB root
```
Apparently that works on mq but not fq_codel or pfifo_fast.

I'll check for mq in the output of ```tc qdisc show dev interfaceA root``` and ```tc qdisc show dev interfaceB root```.
If mq appears, it will skip the ```tc qdisc delete``` commands, preventing the error  response from netlink in syslog.

**Comment by rchac** [comment]
Should now be solved with https://github.com/LibreQoE/LibreQoS/pull/297
Please reopen if not. =)
