### ISSUE TITLE
lqos_node_manager - after error there is no periodic checking of ShapedDevices.csv changes

### ISSUE THREAD

**Issue by interduo** [LibreQoE/LibreQoS#239]
When I:
- damage ShapedDevices.csv (for example by removing one quote)
```
Feb 02 10:01:03 libreqos-new lqos_node_manager[826]: Error: Error reading CSV record: Err(Error(UnequalLengths { pos: Some(Position { byte: 186, line: 3, record: 1 }), expected_len: 13, len>
Feb 02 10:01:03 libreqos-new lqos_node_manager[826]: Error: CSV devode error: At line 3, position 186. Expected 13 fields, found 27
```
then repair it by adding missing quote.

No reloading. I need to reload manualy.

So I think that there is broken periodic checking for ShapedDevices.csv after error occurs.

**Comment by dtaht** [comment]
@interduo all better now?

**Comment by interduo** [comment]
I need some time for testing. I am doing it intesively now. Now for me it looks good.
Monday will show more.

**Comment by interduo** [comment]
I added field at the end to get an error:
```
Feb  6 16:57:08 libreqos-new lqos_node_manager[907]: Error: CSV decode error: At line 3238, position 209667. Expected 13 fields, found 14
Feb  6 16:57:08 libreqos-new lqos_node_manager[907]: Warning: ShapedDevices.csv failed to load, see previous error messages. Reverting to empty set.
```

I removed that errorous field and get:
```
root@libreqos-new:/opt/libreqos/src# ./LibreQoS.py --updateonly
lqosd is running
refreshShapers starting at 06/02/2023 16:57:54
Rust validated ShapedDevices.csv
network.json passed validation
ShapedDevices.csv passed validation
Backed up good config as lastGoodConfig.csv and lastGoodConfig.json
Error: Class id must be in the format (major):(minor), e.g. 1:12
updated
Queue and IP filter partial reload completed in 0 seconds
refreshShapersUpdateOnly completed on 06/02/2023 16:57:56
root@libreqos-new:/opt/libreqos/src# ./LibreQoS.py --updateonly
lqosd is running
refreshShapers starting at 06/02/2023 16:58:11
Rust validated ShapedDevices.csv
network.json passed validation
ShapedDevices.csv passed validation
Backed up good config as lastGoodConfig.csv and lastGoodConfig.json
Queue and IP filter partial reload completed in 0 seconds
refreshShapersUpdateOnly completed on 06/02/2023 16:58:12
```

Why there is an action "Reverting to empty set" after error instead of "I would not make any change because of validation errror" ?

**Comment by interduo** [comment]
After errors occurs "file_watcher" dont check for file changes (or there is just no message in any syslog, lqosd, lqos_node_manager logs).

**Comment by thebracket** [comment]
I can't for the life of me replicate the not loading in the web UI problem: I can break the file, observe the list in the shaped devices page as empty, fix it, and observe that there's data after I hit refresh.

The error message `Error: Class id must be in the format (major):(minor), e.g. 1:12` clued me into something deeper being wrong, so I went digging.

The partial reloader was broken, attempting to use a field that wasn't present in the circuit data. I fixed that for dual-interface mode. The whole update logic needs some reworking for single-interface ("On a stick") mode, so for now I've added an error message telling you not to use partial updates when in `OnAStick` mode.

**Comment by interduo** [comment]
@thebracket something more is needs to be done after last commits:

```
Running Python Version 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
lqosd is running
refreshShapers starting at 16/02/2023 09:24:06
Rust validated ShapedDevices.csv
network.json passed validation
ShapedDevices.csv passed validation
Backed up good config as lastGoodConfig.csv and lastGoodConfig.json
tc class del dev ens16f1np1 classid 0x2:0x6f
tc class del dev ens16f0np0 classid 0x2:0x6f
tc class del dev ens16f1np1 classid 0xa:0x9a
tc class del dev ens16f0np0 classid 0xa:0x9a
tc class add dev ens16f1np1 parent 0x1:0x3 classid 0xa2 htb rate 16Mbit ceil 16Mbit
tc qdisc add dev ens16f1np1 parent 0x1:0xa2 fq_codel
tc class add dev ens16f0np0 parent 0x1:0x3 classid 0xa2 htb rate 2Mbit ceil 2Mbit
tc qdisc add dev ens16f0np0 parent 0x1:0xa2 fq_codel
Traceback (most recent call last):
File "/opt/libreqos/src/./LibreQoS.py", line 1339, in
refreshShapersUpdateOnly()
File "/opt/libreqos/src/./LibreQoS.py", line 1202, in refreshShapersUpdateOnly
addDeviceIPsToFilter(circuit, cpuNumHex)
TypeError: refreshShapersUpdateOnly..addDeviceIPsToFilter() missing 1 required positional argument: 'classId'
```

**Comment by dtaht** [comment]
@interduo we done here?

**Comment by interduo** [comment]
I will check that in few days. I got plan for update to current master state on first weekend on April.
