### ISSUE TITLE
running ./LibreQoS.py causes errors

### ISSUE THREAD

**Issue by interduo** [LibreQoE/LibreQoS#241]
```
root@libreqos-new:/opt/libreqos/src# ./LibreQoS.py
lqosd is running
refreshShapers starting at 02/02/2023 14:51:17
Not first time run since system boot.
Validating input files 'ShapedDevices.csv' and 'network.json'
Rust validated ShapedDevices.csv
network.json passed validation
ShapedDevices.csv passed validation
Backed up good config as lastGoodConfig.csv and lastGoodConfig.json
NIC queues:			16
CPU cores:			16
queuesAvailable set to:	16
Generating parent nodes
Using binpacking module to sort circuits by CPU core
Finished binpacking
Generated parent nodes created
Executing linux TC class/qdisc commands
Executed 13114 linux TC class/qdisc commands
Executed 13114 linux TC class/qdisc commands
Executing XDP-CPUMAP-TC IP filter commands
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', /opt/libreqos/src/rust/lqos_bus/src/bus/client.rs:29:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', /opt/libreqos/src/rust/lqos_bus/src/bus/client.rs:29:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', /opt/libreqos/src/rust/lqos_bus/src/bus/client.rs:29:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'mainthread '' panicked at 'maincalled `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }' panicked at '', /opt/libreqos/src/rust/lqos_bus/src/bus/client.rs:29:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', /opt/libreqos/src/rust/lqos_bus/src/bus/client.rs:29:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', /opt/libreqos/src/rust/lqos_bus/src/bus/client.rs:29:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', /opt/libreqos/src/rust/lqos_bus/src/bus/client.rs:29:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', /opt/libreqos/src/rust/lqos_bus/src/bus/client.rs:29:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', /opt/libreqos/src/rust/lqos_bus/src/bus/client.rs:29:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', /opt/libreqos/src/rust/lqos_bus/src/bus/client.rs:29:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', /opt/libreqos/src/rust/lqos_bus/src/bus/client.rs:29:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', /opt/libreqos/src/rust/lqos_bus/src/bus/client.rs:29:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', /opt/libreqos/src/rust/lqos_bus/src/bus/client.rs:29:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', /opt/libreqos/src/rust/lqos_bus/src/bus/client.rs:29:27
```
after some time service lqosd goes off

**Comment by dtaht** [comment]
you past this? The right answer here is to do exponentaial backoff and retry
