### ISSUE TITLE
UISP intergration error

### ISSUE THREAD

**Issue by Zacgoose** [LibreQoE/LibreQoS#478]
Any ideas? I can't seem to find what would be causing this. All my APs and Stations are in bridge mode as i hand out public IPs via DHCP.

I am running the latest stable UISP 2.3.57
Error:
root@libreqos:/opt/libreqos/src# python3 integrationUISP.py
Running Python Version 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Loading Data from UISP
Compiling Site Bandwidths
Finding AP Capacities
Traceback (most recent call last):
  File "/opt/libreqos/src/integrationUISP.py", line 569, in <module>
    importFromUISP()
  File "/opt/libreqos/src/integrationUISP.py", line 562, in importFromUISP
    case "full": buildFullGraph()
  File "/opt/libreqos/src/integrationUISP.py", line 394, in buildFullGraph
    findApCapacities(devices, siteBandwidth)
  File "/opt/libreqos/src/integrationUISP.py", line 148, in findApCapacities
    if device['identification']['role'] == "ap":
TypeError: string indices must be integers

ISPconfig.py

# UISP integration
automaticImportUISP = True
uispAuthToken = 'REDACTED'

UISPbaseURL = 'https://REDACTED'

uispSite = 'Home'

uispStrategy = "full"

uispSuspendedStrategy = "none"

airMax_capacity = 0.65
ltu_capacity = 0.90

excludeSites = ['Vasse Office']

findIPv6usingMikrotik = False

bandwidthOverheadFactor = 1.05

committedBandwidthMultiplier = 0.98

exceptionCPEs = {}

**Comment by Zacgoose** [comment]
Okay so turns out it wants the NMS API key not the CRM API key.
Can this please be made more clear in the docs?
