### ISSUE TITLE
v1.5-beta: error when building packages using build_rust.sh

### ISSUE THREAD

**Issue by interduo** [LibreQoE/LibreQoS#503]
I did: 
`git clone -b develop https://github.com/LibreQoE/LibreQoS`

Then run: `./build_rust.sh`

First I get an error: rustup is not installed at '/root/.cargo'
Secondly I get compile errors for (error: failed to run custom build command for libbpf-sys v1.4.2+v1.4.2) - full log below.

```
./build_rust.sh 
bpftool found.
pkg-config found.
LLVM/clang is not installed.
Let's try to install it
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
llvm is already the newest version (1:18.0-59~exp2).
libelf-dev is already the newest version (0.190-1.1build4).
gcc is already the newest version (4:13.2.0-7ubuntu1).
gcc-multilib is already the newest version (4:13.2.0-7ubuntu1).
libbpf-dev is already the newest version (1:1.3.0-2build2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Checking that Rust is uptodate
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
error: rustup is not installed at '/root/.cargo'
Please wait while the system is compiled. Service will not be interrupted during this stage.
   Compiling hyper-tls v0.5.0
   Compiling lqos_config v0.1.0 (/root/LibreQoS-1.5-beta-1/src/rust/lqos_config)
   Compiling libbpf-sys v1.4.2+v1.4.2
   Compiling jemalloc-sys v0.5.4+5.3.0-patched
   Compiling regex v1.10.5
   Compiling anstream v0.6.14
   Compiling flate2 v1.0.30
   Compiling signal-hook v0.3.17
   Compiling lqosd v0.1.0 (/root/LibreQoS-1.5-beta-1/src/rust/lqosd)
error: failed to run custom build command for `libbpf-sys v1.4.2+v1.4.2`

Caused by:
  process didn't exit successfully: `/root/LibreQoS-1.5-beta-1/src/rust/target/release/build/libbpf-sys-c04cb84a254e91e0/build-script-build` (exit status: 101)
  --- stdout
  Using feature vendored-libbpf=true
  Using feature vendored-libelf=false
  Using feature vendored-zlib=false
  Using feature static-libbpf=true
  Using feature static-libelf=false
  Using feature static-zlib=false

  --- stderr
  thread 'main' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libbpf-sys-1.4.2+v1.4.2/build.rs:96:9:
  make is required to compile libbpf-sys with the selected set of features
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `lqosd v0.1.0 (/root/LibreQoS-1.5-beta-1/src/rust/lqosd)`

Caused by:
  process didn't exit successfully: `/root/LibreQoS-1.5-beta-1/src/rust/target/release/build/lqosd-70cd55068400e6e6/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at lqosd/build.rs:4:75:
  called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: use of deprecated type alias `toml_edit::Document`: Replaced with `DocumentMut`
 --> lqos_config/src/etc/etclqos_migration.rs:4:17
  |
4 | use toml_edit::{Document, value};
  |                 ^^^^^^^^
  |
  = note: `#[warn(deprecated)]` on by default

warning: use of deprecated type alias `toml_edit::Document`: Replaced with `DocumentMut`
   --> lqos_config/src/etc/etclqos_migration.rs:226:32
    |
226 |     let document = raw.parse::<Document>();
    |                                ^^^^^^^^

warning: use of deprecated type alias `toml_edit::Document`: Replaced with `DocumentMut`
   --> lqos_config/src/etc/etclqos_migration.rs:270:31
    |
270 | fn check_config(cfg_doc: &mut Document, cfg: &mut EtcLqos) {
    |                               ^^^^^^^^

warning: use of deprecated type alias `toml_edit::Document`: Replaced with `DocumentMut`
   --> lqos_config/src/etc/etclqos_migration.rs:175:32
    |
175 |     let document = raw.parse::<Document>();
    |                                ^^^^^^^^

warning: use of deprecated type alias `toml_edit::Document`: Replaced with `DocumentMut`
   --> lqos_config/src/etc/etclqos_migration.rs:202:37
    |
202 |   pub fn save(&self, document: &mut Document) -> Result<(), EtcLqosErro...
    |                                     ^^^^^^^^

warning: use of deprecated type alias `toml_edit::Document`: Replaced with `DocumentMut`
 --> lqos_config/src/etc/migration.rs:9:16
  |
9 | use toml_edit::Document;
  |                ^^^^^^^^

warning: use of deprecated type alias `toml_edit::Document`: Replaced with `DocumentMut`
  --> lqos_config/src/etc/migration.rs:31:18
   |
31 |         .parse::<Document>()
   |                  ^^^^^^^^

warning: `lqos_config` (lib) generated 7 warnings
error: failed to run custom build command for `jemalloc-sys v0.5.4+5.3.0-patched`

Caused by:
  process didn't exit successfully: `/root/LibreQoS-1.5-beta-1/src/rust/target/release/build/jemalloc-sys-d8ebc885bcb38650/build-script-build` (exit status: 101)
  --- stdout
  TARGET=x86_64-unknown-linux-gnu
  HOST=x86_64-unknown-linux-gnu
  NUM_JOBS=16
  OUT_DIR="/root/LibreQoS-1.5-beta-1/src/rust/target/release/build/jemalloc-sys-35ec6fe079618f13/out"
  BUILD_DIR="/root/LibreQoS-1.5-beta-1/src/rust/target/release/build/jemalloc-sys-35ec6fe079618f13/out/build"
  SRC_DIR="/root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/jemalloc-sys-0.5.4+5.3.0-patched"
  cargo:rustc-cfg=prefixed
  cargo:rerun-if-env-changed=JEMALLOC_OVERRIDE
  OPT_LEVEL = Some(3)
  TARGET = Some(x86_64-unknown-linux-gnu)
  HOST = Some(x86_64-unknown-linux-gnu)
  cargo:rerun-if-env-changed=CC_x86_64-unknown-linux-gnu
  CC_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CC_x86_64_unknown_linux_gnu
  CC_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some(false)
  CARGO_CFG_TARGET_FEATURE = Some(fxsr,sse,sse2)
  cargo:rerun-if-env-changed=CFLAGS_x86_64-unknown-linux-gnu
  CFLAGS_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64_unknown_linux_gnu
  CFLAGS_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  CC="cc"
  CFLAGS="-O3 -ffunction-sections -fdata-sections -fPIC -m64 -Wall"
  JEMALLOC_REPO_DIR="jemalloc"
  cargo:rerun-if-env-changed=JEMALLOC_SYS_WITH_MALLOC_CONF
  cargo:rerun-if-env-changed=JEMALLOC_SYS_WITH_LG_PAGE
  cargo:rerun-if-env-changed=JEMALLOC_SYS_WITH_LG_HUGEPAGE
  cargo:rerun-if-env-changed=JEMALLOC_SYS_WITH_LG_QUANTUM
  cargo:rerun-if-env-changed=JEMALLOC_SYS_WITH_LG_VADDR
  --with-jemalloc-prefix=_rjem_
  running: cd "/root/LibreQoS-1.5-beta-1/src/rust/target/release/build/jemalloc-sys-35ec6fe079618f13/out/build" && CC="cc" CFLAGS="-O3 -ffunction-sections -fdata-sections -fPIC -m64 -Wall" CPPFLAGS="-O3 -ffunction-sections -fdata-sections -fPIC -m64 -Wall" LDFLAGS="-O3 -ffunction-sections -fdata-sections -fPIC -m64 -Wall" "sh" "/root/LibreQoS-1.5-beta-1/src/rust/target/release/build/jemalloc-sys-35ec6fe079618f13/out/build/configure" "--disable-cxx" "--enable-doc=no" "--enable-shared=no" "--with-jemalloc-prefix=_rjem_" "--with-private-namespace=_rjem_" "--host=x86_64-unknown-linux-gnu" "--build=x86_64-unknown-linux-gnu" "--prefix=/root/LibreQoS-1.5-beta-1/src/rust/target/release/build/jemalloc-sys-35ec6fe079618f13/out"
  checking for xsltproc... false
  checking for x86_64-unknown-linux-gnu-gcc... cc
  checking whether the C compiler works... yes
  checking for C compiler default output file name... a.out
  checking for suffix of executables... 
  checking whether we are cross compiling... no
  checking for suffix of object files... o
  checking whether we are using the GNU C compiler... yes
  checking whether cc accepts -g... yes
  checking for cc option to accept ISO C89... none needed
  checking whether compiler is cray... no
  checking whether compiler supports -std=gnu11... yes
  checking whether compiler supports -Werror=unknown-warning-option... no
  checking whether compiler supports -Wall... yes
  checking whether compiler supports -Wextra... yes
  checking whether compiler supports -Wshorten-64-to-32... no
  checking whether compiler supports -Wsign-compare... yes
  checking whether compiler supports -Wundef... yes
  checking whether compiler supports -Wno-format-zero-length... yes
  checking whether compiler supports -Wpointer-arith... yes
  checking whether compiler supports -Wno-missing-braces... yes
  checking whether compiler supports -Wno-missing-field-initializers... yes
  checking whether compiler supports -Wno-missing-attributes... yes
  checking whether compiler supports -pipe... yes
  checking whether compiler supports -g3... yes
  checking how to run the C preprocessor... cc -E
  checking for grep that handles long lines and -e... /usr/bin/grep
  checking for egrep... /usr/bin/grep -E
  checking for ANSI C header files... yes
  checking for sys/types.h... yes
  checking for sys/stat.h... yes
  checking for stdlib.h... yes
  checking for string.h... yes
  checking for memory.h... yes
  checking for strings.h... yes
  checking for inttypes.h... yes
  checking for stdint.h... yes
  checking for unistd.h... yes
  checking whether byte ordering is bigendian... no
  checking size of void *... 8
  checking size of int... 4
  checking size of long... 8
  checking size of long long... 8
  checking size of intmax_t... 8
  checking build system type... x86_64-unknown-linux-gnu
  checking host system type... x86_64-unknown-linux-gnu
  checking whether pause instruction is compilable... yes
  checking number of significant virtual address bits... 48
  checking for x86_64-unknown-linux-gnu-ar... no
  checking for ar... ar
  checking for x86_64-unknown-linux-gnu-nm... no
  checking for nm... nm
  checking for gawk... gawk
  checking malloc.h usability... yes
  checking malloc.h presence... yes
  checking for malloc.h... yes
  checking whether malloc_usable_size definition can use const argument... no
  checking for library containing log... -lm
  checking whether __attribute__ syntax is compilable... yes
  checking whether compiler supports -fvisibility=hidden... yes
  checking whether compiler supports -fvisibility=hidden... no
  checking whether compiler supports -Werror... yes
  checking whether compiler supports -herror_on_warning... no
  checking whether tls_model attribute is compilable... yes
  checking whether compiler supports -Werror... yes
  checking whether compiler supports -herror_on_warning... no
  checking whether alloc_size attribute is compilable... yes
  checking whether compiler supports -Werror... yes
  checking whether compiler supports -herror_on_warning... no
  checking whether format(gnu_printf, ...) attribute is compilable... yes
  checking whether compiler supports -Werror... yes
  checking whether compiler supports -herror_on_warning... no
  checking whether format(printf, ...) attribute is compilable... yes
  checking whether compiler supports -Werror... yes
  checking whether compiler supports -herror_on_warning... no
  checking whether format(printf, ...) attribute is compilable... yes
  checking whether compiler supports -Wimplicit-fallthrough... yes
  checking whether fallthrough attribute is compilable... yes
  checking whether compiler supports -Wimplicit-fallthrough... yes
  checking whether compiler supports -Wimplicit-fallthrough... no
  checking whether compiler supports -Werror... yes
  checking whether compiler supports -herror_on_warning... no
  checking whether cold attribute is compilable... yes
  checking whether vm_make_tag is compilable... no
  checking for a BSD-compatible install... /usr/bin/install -c
  checking for x86_64-unknown-linux-gnu-ranlib... no
  checking for ranlib... ranlib
  checking for ld... /usr/bin/ld
  checking for autoconf... false
  checking for memalign... yes
  checking for valloc... yes
  checking for malloc_size... no
  checking whether compiler supports -O3... yes
  checking whether compiler supports -O3... no
  checking whether compiler supports -funroll-loops... yes
  checking configured backtracing method... N/A
  checking for sbrk... yes
  checking whether utrace(2) is compilable... no
  checking whether utrace(2) with label is compilable... no
  checking whether a program using __builtin_unreachable is compilable... yes
  checking whether a program using __builtin_ffsl is compilable... yes
  checking whether a program using __builtin_popcountl is compilable... yes
  checking LG_PAGE... 12
  checking pthread.h usability... yes
  checking pthread.h presence... yes
  checking for pthread.h... yes
  checking for pthread_create in -lpthread... yes
  checking dlfcn.h usability... yes
  checking dlfcn.h presence... yes
  checking for dlfcn.h... yes
  checking for dlsym... yes
  checking whether pthread_atfork(3) is compilable... yes
  checking whether pthread_setname_np(3) is compilable... yes
  checking whether pthread_getname_np(3) is compilable... yes
  checking whether pthread_get_name_np(3) is compilable... no
  checking for library containing clock_gettime... none required
  checking whether clock_gettime(CLOCK_MONOTONIC_COARSE, ...) is compilable... yes
  checking whether clock_gettime(CLOCK_MONOTONIC, ...) is compilable... yes
  checking whether mach_absolute_time() is compilable... no
  checking whether clock_gettime(CLOCK_REALTIME, ...) is compilable... yes
  checking whether compiler supports -Werror... yes
  checking whether syscall(2) is compilable... yes
  checking for secure_getenv... yes
  checking for sched_getcpu... yes
  checking for sched_setaffinity... yes
  checking for issetugid... no
  checking for _malloc_thread_cleanup... no
  checking for _pthread_mutex_init_calloc_cb... no
  checking for memcntl... no
  checking for TLS... yes
  checking whether C11 atomics is compilable... yes
  checking whether GCC __atomic atomics is compilable... yes
  checking whether GCC 8-bit __atomic atomics is compilable... yes
  checking whether GCC __sync atomics is compilable... yes
  checking whether GCC 8-bit __sync atomics is compilable... yes
  checking whether Darwin OSAtomic*() is compilable... no
  checking whether madvise(2) is compilable... yes
  checking whether madvise(..., MADV_FREE) is compilable... yes
  checking whether madvise(..., MADV_DONTNEED) is compilable... yes
  checking whether madvise(..., MADV_DO[NT]DUMP) is compilable... yes
  checking whether madvise(..., MADV_[NO]HUGEPAGE) is compilable... yes
  checking whether madvise(..., MADV_[NO]CORE) is compilable... no
  checking whether mprotect(2) is compilable... yes
  checking for __builtin_clz... yes
  checking whether Darwin os_unfair_lock_*() is compilable... no
  checking whether glibc malloc hook is compilable... no
  checking whether glibc memalign hook is compilable... no
  checking whether pthreads adaptive mutexes is compilable... yes
  checking whether compiler supports -D_GNU_SOURCE... yes
  checking whether compiler supports -Werror... yes
  checking whether compiler supports -herror_on_warning... no
  checking whether strerror_r returns char with gnu source is compilable... yes
  checking for stdbool.h that conforms to C99... yes
  checking for _Bool... yes
  configure: creating ./config.status
  config.status: creating Makefile
  config.status: creating jemalloc.pc
  config.status: creating doc/html.xsl
  config.status: creating doc/manpages.xsl
  config.status: creating doc/jemalloc.xml
  config.status: creating include/jemalloc/jemalloc_macros.h
  config.status: creating include/jemalloc/jemalloc_protos.h
  config.status: creating include/jemalloc/jemalloc_typedefs.h
  config.status: creating include/jemalloc/internal/jemalloc_preamble.h
  config.status: creating test/test.sh
  config.status: creating test/include/test/jemalloc_test.h
  config.status: creating config.stamp
  config.status: creating bin/jemalloc-config
  config.status: creating bin/jemalloc.sh
  config.status: creating bin/jeprof
  config.status: creating include/jemalloc/jemalloc_defs.h
  config.status: creating include/jemalloc/internal/jemalloc_internal_defs.h
  config.status: creating test/include/test/jemalloc_test_defs.h
  config.status: executing include/jemalloc/internal/public_symbols.txt commands
  config.status: executing include/jemalloc/internal/private_symbols.awk commands
  config.status: executing include/jemalloc/internal/private_symbols_jet.awk commands
  config.status: executing include/jemalloc/internal/public_namespace.h commands
  config.status: executing include/jemalloc/internal/public_unnamespace.h commands
  config.status: executing include/jemalloc/jemalloc_protos_jet.h commands
  config.status: executing include/jemalloc/jemalloc_rename.h commands
  config.status: executing include/jemalloc/jemalloc_mangle.h commands
  config.status: executing include/jemalloc/jemalloc_mangle_jet.h commands
  config.status: executing include/jemalloc/jemalloc.h commands
  ===============================================================================
  jemalloc version   : 5.3.0-0-g54eaed1d8b56b1aa528be3bdd1877e59c56fa90c
  library revision   : 2

  CONFIG             : --disable-cxx --enable-doc=no --enable-shared=no --with-jemalloc-prefix=_rjem_ --with-private-namespace=_rjem_ --host=x86_64-unknown-linux-gnu --build=x86_64-unknown-linux-gnu --prefix=/root/LibreQoS-1.5-beta-1/src/rust/target/release/build/jemalloc-sys-35ec6fe079618f13/out build_alias=x86_64-unknown-linux-gnu host_alias=x86_64-unknown-linux-gnu CC=cc 'CFLAGS=-O3 -ffunction-sections -fdata-sections -fPIC -m64 -Wall' 'LDFLAGS=-O3 -ffunction-sections -fdata-sections -fPIC -m64 -Wall' 'CPPFLAGS=-O3 -ffunction-sections -fdata-sections -fPIC -m64 -Wall'
  CC                 : cc
  CONFIGURE_CFLAGS   : -std=gnu11 -Wall -Wextra -Wsign-compare -Wundef -Wno-format-zero-length -Wpointer-arith -Wno-missing-braces -Wno-missing-field-initializers -Wno-missing-attributes -pipe -g3 -fvisibility=hidden -Wimplicit-fallthrough -O3 -funroll-loops
  SPECIFIED_CFLAGS   : -O3 -ffunction-sections -fdata-sections -fPIC -m64 -Wall
  EXTRA_CFLAGS       : 
  CPPFLAGS           : -O3 -ffunction-sections -fdata-sections -fPIC -m64 -Wall -D_GNU_SOURCE -D_REENTRANT
  CXX                : 
  CONFIGURE_CXXFLAGS : 
  SPECIFIED_CXXFLAGS : 
  EXTRA_CXXFLAGS     : 
  LDFLAGS            : -O3 -ffunction-sections -fdata-sections -fPIC -m64 -Wall
  EXTRA_LDFLAGS      : 
  DSO_LDFLAGS        : -shared -Wl,-soname,$(@F)
  LIBS               : -lm  -pthread
  RPATH_EXTRA        : 

  XSLTPROC           : false
  XSLROOT            : 

  PREFIX             : /root/LibreQoS-1.5-beta-1/src/rust/target/release/build/jemalloc-sys-35ec6fe079618f13/out
  BINDIR             : /root/LibreQoS-1.5-beta-1/src/rust/target/release/build/jemalloc-sys-35ec6fe079618f13/out/bin
  DATADIR            : /root/LibreQoS-1.5-beta-1/src/rust/target/release/build/jemalloc-sys-35ec6fe079618f13/out/share
  INCLUDEDIR         : /root/LibreQoS-1.5-beta-1/src/rust/target/release/build/jemalloc-sys-35ec6fe079618f13/out/include
  LIBDIR             : /root/LibreQoS-1.5-beta-1/src/rust/target/release/build/jemalloc-sys-35ec6fe079618f13/out/lib
  MANDIR             : /root/LibreQoS-1.5-beta-1/src/rust/target/release/build/jemalloc-sys-35ec6fe079618f13/out/share/man

  srcroot            : 
  abs_srcroot        : /root/LibreQoS-1.5-beta-1/src/rust/target/release/build/jemalloc-sys-35ec6fe079618f13/out/build/
  objroot            : 
  abs_objroot        : /root/LibreQoS-1.5-beta-1/src/rust/target/release/build/jemalloc-sys-35ec6fe079618f13/out/build/

  JEMALLOC_PREFIX    : _rjem_
  JEMALLOC_PRIVATE_NAMESPACE
                     : _rjem_je_
  install_suffix     : 
  malloc_conf        : 
  documentation      : 0
  shared libs        : 0
  static libs        : 1
  autogen            : 0
  debug              : 0
  stats              : 1
  experimental_smallocx : 0
  prof               : 0
  prof-libunwind     : 0
  prof-libgcc        : 0
  prof-gcc           : 0
  fill               : 1
  utrace             : 0
  xmalloc            : 0
  log                : 0
  lazy_lock          : 0
  cache-oblivious    : 1
  cxx                : 0
  ===============================================================================
  running: cd "/root/LibreQoS-1.5-beta-1/src/rust/target/release/build/jemalloc-sys-35ec6fe079618f13/out/build" && "make" "-j" "16"

  --- stderr
  thread 'main' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/jemalloc-sys-0.5.4+5.3.0-patched/build.rs:347:19:
  failed to execute command: No such file or directory (os error 2)
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Cargo build failed. Exiting with code 1.
```

**Comment by interduo** [comment]
@thebracket after Your suggestions, I rewrite PR#502 then:
```
git clone -b patch-32 https://github.com/interduo/LibreQoS LibreQoS;
cd LibreQoS/src/;
./build_rust.sh
```

Now only compilation errors in:
```
error: failed to run custom build command for `libbpf-sys v1.4.2+v1.4.2`

Caused by:
  process didn't exit successfully: `/root/LibreQoS/src/rust/target/release/build/libbpf-sys-c04cb84a254e91e0/build-script-build` (exit status: 101)
  --- stdout
  Using feature vendored-libbpf=true
  Using feature vendored-libelf=false
  Using feature vendored-zlib=false
  Using feature static-libbpf=true
  Using feature static-libelf=false
  Using feature static-zlib=false

  --- stderr
  thread 'main' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libbpf-sys-1.4.2+v1.4.2/build.rs:96:9:
  make is required to compile libbpf-sys with the selected set of features
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by thebracket** [comment]
This is what happens when you install the Rust toolchain via `apt` instead of rustup. The package version doesn't do useful things like actually installing the compiler for your architecture, the cargo toolchain, etc. We've updated `build_rust` to tell you to do it, and the documentation has included that for a long time - so I'm closing this one.

**Comment by interduo** [comment]
Is it possible to check from what source cargo/rustup comes from somehow?

**Comment by interduo** [comment]
> This is what happens when you install the Rust toolchain via `apt` instead of rustup. The package version doesn't do useful things like actually installing the compiler for your architecture, the cargo toolchain, etc. We've updated `build_rust` to tell you to do it, and the documentation has included that for a long time - so I'm closing this one.

This is not the case - @thebracket look:
# clean the os from rust/libreqos packages/repos/dir
`apt purge cargo rustup* libreqos && rm -rf ~/.cargo ~/.rustup ~/LibreQoS /opt/libreqos`

# clone src code
```
git clone -b develop git@github.com:LibreQoE/LibreQoS.git && cd ~/LibreQoS
git remote add interduo git@github.com:interduo/LibreQoS.git && git fetch interduo && git pull interduo patch-33
```
# try to build rust
`cd ~/LibreQoS/src && ./build_rust.sh`

#see error message so run:
`curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`

```
$ rustup --version
rustup 1.27.1 (54dd3d00f 2024-04-24)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.79.0 (129f3b996 2024-06-10)`
```

# again `./build_rust.sh &>build_log_1650`
see whole build log on: http://kłopotek.pl/build_log_1650

If I didn't clean something I will: "sprinkle ashes on my head"

**Comment by interduo** [comment]
@thebracket, please see this compile errors first, maybe its the source of other bugs

**Comment by interduo** [comment]
> This is what happens when you install the Rust toolchain via `apt` instead of rustup. The package version doesn't do useful things like actually installing the compiler for your architecture, the cargo toolchain, etc. We've updated `build_rust` to tell you to do it, and the documentation has included that for a long time - so I'm closing this one.

@thebracket tried to resolve that few times in different way. Could You give me advice/guide me how to ommit those warnings/errors?
I did: ```apt purge cargo``` and 
```apt purge rustup```

**Comment by thebracket** [comment]
I only see warnings there, nothing that should stop it from compiling?

**Comment by interduo** [comment]
In my instance there is no QoS policy applied, i bet (probably bad) that one of those warnings is responsible for that.

At what moment You clean warnings in code before release beta or rc1?

**Comment by thebracket** [comment]
> In my instance there is no QoS policy applied, i bet (probably bad) that one of those warnings is responsible for that.

Every single one of those warnings is "you didn't use a variable" or "you used a deprecated code path in the TOML reader" - nothing there that'll stop shaping from happening. My bet would be you need to run `LibreQoS.py` and check the output?

> At what moment You clean warnings in code before release beta or rc1?

Towards the end of the beta cycle. They are harmless, but irritating.

**Comment by interduo** [comment]
Ok closing this.
