### ISSUE TITLE
Running LibreQoS.py from other place like it's dir gives an error - small improvment needed

### ISSUE THREAD

**Issue by interduo** [LibreQoE/LibreQoS#54]
```
python3 /root/LibreQoS/v1.1/LibreQoS.py 
Traceback (most recent call last):
  File "/root/LibreQoS/v1.1/LibreQoS.py", line 243, in <module>
    refreshShapers()
  File "/root/LibreQoS/v1.1/LibreQoS.py", line 45, in refreshShapers
    with open('Shaper.csv') as csv_file:
FileNotFoundError: [Errno 2] No such file or directory: 'Shaper.csv'
```

root@rty-libreqos:~# ls -la /root/LibreQoS/v1.1/Shaper.csv 
`-rw-r--r-- 1 root root 564 Aug 31 12:07 /root/LibreQoS/v1.1/Shaper.csv`

Script should:
- use config file declared in parameter `--configShaper=Shaper.csv --configNetwork=network.json`,
- if not is avaiable in parameter then use file from directory of the script,
- if no is avaiable print an error,

This would be small improvement because if we would like to run it's from crontab we have to use bash wrapper script.

**Comment by dtaht** [comment]
a short term fix by using crontab, "cd therightdir; LibreQos whatever".

Certainly having more options that make sense would be good.

**Comment by interduo** [comment]
The same fix should be done for `lqTools.py`.

**Comment by dtaht** [comment]
done?

also lqos is shorter... - symlink?

**Comment by interduo** [comment]
This is still a thing.

**Comment by interduo** [comment]
`lq.sh` ?

**Comment by dtaht** [comment]
Someday it wont be a shell script. lq has a high probability of colliding with something...

**Comment by interduo** [comment]
Sorry I mean `lq.py`

**Comment by dtaht** [comment]
I think we have settled for lqos as the script name. AS for the locking issue?

**Comment by interduo** [comment]
`lqos.py` is a good name.

**Comment by rchac** [comment]
Fixed with https://github.com/LibreQoE/LibreQoS/commit/ed07a4666b62d222ed3dbb44c3a647f67892baaf

**Comment by interduo** [comment]
```
lqosd is running
refreshShapers starting at 07/02/2023 15:20:13
Rust validated ShapedDevices.csv
Traceback (most recent call last):
  File "/opt/libreqos/src/LibreQoS.py", line 1331, in <module>
    refreshShapersUpdateOnly()
  File "/opt/libreqos/src/LibreQoS.py", line 928, in refreshShapersUpdateOnly
    if (validateNetworkAndDevices() == True):
  File "/opt/libreqos/src/LibreQoS.py", line 139, in validateNetworkAndDevices
    with open('network.json') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'network.json'
```

**Comment by rchac** [comment]
Just to better understand, you're wanting this ability so that you can run from crontab instead of systemd?

**Comment by interduo** [comment]
I would like to have reloading done immediately after uploading file - so I run this magic command through SSH.

**Comment by rchac** [comment]
Is it possible to just SCP the ShapedDevices.csv file to /opt/libreqos then run ```--updateonly```? Both the python and rust side look for a bunch of files to be available to them in the /opt/libreqos/src folder.

**Comment by interduo** [comment]
Running command:
`root@libreqos:~# /opt/libreqos/src/LibreQoS.py --updateonly`

generates an error:
```
Running Python Version 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
lqosd is running
lqosd is running
refreshShapers starting at 21/03/2023 16:24:47
Rust validated ShapedDevices.csv
Traceback (most recent call last):
  File "/opt/libreqos/src/LibreQoS.py", line 1369, in <module>
    refreshShapersUpdateOnly()
  File "/opt/libreqos/src/LibreQoS.py", line 952, in refreshShapersUpdateOnly
    if (validateNetworkAndDevices() == True):
  File "/opt/libreqos/src/LibreQoS.py", line 140, in validateNetworkAndDevices
    with open('network.json') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'network.json'

```

**Comment by interduo** [comment]
@rchac

```
root@libreqos:/opt/libreqos/src# ls -la network.json 
-rw-r--r-- 1 root root 3 Jan 20 14:20 network.json
It only throws an error if I run command from other dir than /opt/libreqos/src
```

**Comment by dtaht** [comment]
This looks complete?

**Comment by interduo** [comment]
No it isn't.

**Comment by interduo** [comment]
Still needs an improvement.

```
root@libreqos-beta:~# /opt/libreqos/src/LibreQoS.py 
Running Python Version 3.12.3 (main, Jul 31 2024, 17:43:48) [GCC 13.2.0]
lqosd is running
Configuration from /etc/lqos.conf is usable
refreshShapers starting at 12/08/2024 13:50:52
First time run since system boot.
Validating input files 'ShapedDevices.csv' and 'network.json'
Rust validated ShapedDevices.csv
Traceback (most recent call last):
  File "/opt/libreqos/src/LibreQoS.py", line 1194, in <module>
    refreshShapers()
  File "/opt/libreqos/src/LibreQoS.py", line 477, in refreshShapers
    if (validateNetworkAndDevices() == True):
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/libreqos/src/LibreQoS.py", line 166, in validateNetworkAndDevices
    with open('network.json') as file:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'network.json'
```
