### ISSUE TITLE
v1.5-beta2: web login problems after update

### ISSUE THREAD

**Issue by interduo** [LibreQoE/LibreQoS#544]
Reproduction:
- login to WEB,
- do upgrade via SSH,
- completly remove lqos, install from the scrach on the same VM,
- try to login via WEB

On internet browser:
![image](https://github.com/user-attachments/assets/cc79f88a-9c70-4d20-8864-eb4cdd4d07e3)

In lqosd logs:
```
Aug 06 08:42:17 libreqos-beta lqosd[109759]: thread 'tokio-runtime-worker' panicked at lqosd/src/node_manager/auth.rs:41:63:
Aug 06 08:42:17 libreqos-beta lqosd[109759]: called `Result::unwrap()` on an `Err` value: InvalidToken
Aug 06 08:42:22 libreqos-beta lqosd[109759]: [2024-08-06T06:42:22Z WARN  lqos_config::authentication] Token 05ca9eac-313b-424d-8300-1976486141a4 not found, invalid data access >
Aug 06 08:42:22 libreqos-beta lqosd[109759]: thread 'tokio-runtime-worker' panicked at lqosd/src/node_manager/auth.rs:41:63:
Aug 06 08:42:22 libreqos-beta lqosd[109759]: called `Result::unwrap()` on an `Err` value: InvalidToken
```

Suggested solution: If no session token is found we should redirect user to login page instead showing an empty response.

Workaround for that: use incognito mode or clean web files in internet browser (chrome/firefox).

**Comment by rchac** [comment]
Fixed as of v1.5-beta-7
