### ISSUE TITLE
Allow data collecting from LibreQoS into monitoring tools

### ISSUE THREAD

**Issue by interduo** [LibreQoE/LibreQoS#75]
I would like to show graphs provided by LibreQoS in our CRM.
@rchac what metod do You prefer to do things like that?

**Comment by rchac** [comment]
I'd recommend to have some script or something to pull stats from InfluxDB, which LibreQoS stores bandwidth data to. It stores data over time so you can neatly graph it easily.

**Comment by interduo** [comment]
Is it possible to retrieve InfluxDB subscriber data by API?

**Comment by rchac** [comment]
Yes! https://docs.influxdata.com/influxdb/v2.4/reference/api/

**Comment by interduo** [comment]
@rchac what software do You use to make graphs of retrieved data from API.

**Comment by rchac** [comment]
InfluxDB [has a UI built-in](https://raw.githubusercontent.com/rchac/LibreQoS/main/docs/v1.1-alpha-preview.jpg), so there is often no need to use the API

**Comment by interduo** [comment]
Yes I know but I would like to show graphs into CRM.
I've got this done now - it's very useful for debugging customer networking issues.

**Comment by rchac** [comment]
Ah ok gotcha. That is a very good idea for debugging!

**Comment by interduo** [comment]
I dont see option for exporting graphs as an images in influxdb and i think that it would be better to generate graphs in our CRM from retrieved data (because of zooming and other features or things that could be done in future with them).

**Comment by interduo** [comment]
I think that the influxdb (here on QoS Engine) is a bit overfeature (it should be marked as optional)
If I am looking at current resources usage from influxdb - there is almost 7GB - please this is not place in this VM for this.

This would generates more problems, many thoughts or at least much work to do with some ram usage / disk space monitoring. (more than cons).

In my opinion we should get opportunity to share circuit traffic data to zabbix/librenms/cacti/sth_else_monitoring_tool and there do the magic (graphing,counting).

For this we need some constant identifier when adding customer - that would not change after reloading, adding, removing customers from beggining of ShapedDevices.csv, (not the classid could change when we mix customers in rows, or customer changes it plan).

Then we could prepare gathering data whitch could be used after with:
- zabbix_sender (agent installed on LibreQoS for fast sending  data to monioring tool),
- snmpd
- cacti remote poller
or other solutions for network monitoring tool.

**Comment by interduo** [comment]
I see `graphBandwidth.py` could You add `--debug` and then just print on the screen the data whitch are transfered to stats?

**Comment by interduo** [comment]
There would be also helpful if we got only error:
`urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fdfb544db70>: Failed to establish a new connection: [Errno 111] Connection refused`

instead of:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/LibreQoS2/v1.2/graphBandwidth.py", line 418, in <module>
    refreshBandwidthGraphs()
  File "/root/LibreQoS2/v1.2/graphBandwidth.py", line 392, in refreshBandwidthGraphs
    write_api.write(bucket=influxDBBucket, record=queriesToSend)
  File "/usr/local/lib/python3.10/dist-packages/influxdb_client/client/write_api.py", line 365, in write
    results = list(map(write_payload, payloads.items()))
  File "/usr/local/lib/python3.10/dist-packages/influxdb_client/client/write_api.py", line 363, in write_payload
    return self._post_write(_async_req, bucket, org, final_string, payload[0])
  File "/usr/local/lib/python3.10/dist-packages/influxdb_client/client/write_api.py", line 474, in _post_write
    return self._write_service.post_write(org=org, bucket=bucket, body=body, precision=precision,
  File "/usr/local/lib/python3.10/dist-packages/influxdb_client/service/write_service.py", line 62, in post_write
    (data) = self.post_write_with_http_info(org, bucket, body, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.10/dist-packages/influxdb_client/service/write_service.py", line 92, in post_write_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.10/dist-packages/influxdb_client/_sync/api_client.py", line 343, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.10/dist-packages/influxdb_client/_sync/api_client.py", line 173, in __call_api
    response_data = self.request(
  File "/usr/local/lib/python3.10/dist-packages/influxdb_client/_sync/api_client.py", line 388, in request
    return self.rest_client.POST(url,
  File "/usr/local/lib/python3.10/dist-packages/influxdb_client/_sync/rest.py", line 307, in POST
    return self.request("POST", url,
  File "/usr/local/lib/python3.10/dist-packages/influxdb_client/_sync/rest.py", line 216, in request
    r = self.pool_manager.request(
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 78, in request
    return self.request_encode_body(
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 507, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 719, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fdfb544db70>: Failed to establish a new connection: [Errno 111] Connection refused
```

**Comment by dtaht** [comment]
I'm punting this to 1.4. I would like to be able to do detailed offline analysis via classic postgres SQL and related tooling myself, and SNMP is useful, as is xabbix, but...

**Comment by interduo** [comment]
The main thing is that we should go out with influx and use external tools for big instances for CPU savings.

**Comment by interduo** [comment]
1. We generate `${STATS_FILE}` with conntent:
Each line of the `${STATS_FILE}` must contain 4 whitespace delimited entries: <hostname> <key> <timestamp> <value>

(every stats read from counters need to just add lines and not replace whole file - If zabbix would be unavaiable then the file will have all missing values from stats and there we would not have a holes in LibreQoS generated graphs. After error code 0 in ealier command we could delete this file.)

2. The example of zabbix integration could be:
```
zabbix_sender -z ${ZABBIX_SERVER} -T -i ${STATS_FILE}
if [ $? -eq 0 ]
then 
  rm ${STATS_FILE}
fi
```

**Comment by rchac** [comment]
Current Solution: LTS
